services:
  app:
    build: .
    # to run localhost
    ports:
      - 3000:3000   
    volumes:
      - .:/home/node/app


  # mysql:
  #   image: mysql:8.0.37-debian
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=nest
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql